### ISSUE TITLE
cling is not properly worked in Windows conda python 2.7

### ISSUE THREAD

**Issue by ouxiaogu** [conda-forge/cling-feedstock#9]
I use conda python 2.7, install cling by this command in Window system:

`conda install -c conda-forge cling`

Jupyter notebook will be crashed, after I create a new C++ notebook, not matter C++11, 14 or 17.

`
Traceback (most recent call last):
  File "~\AppData\Local\Anaconda2\Scripts\jupyter-cling-kernel-script.py", line 2, in <module>
    from clingkernel import main
  File "~\AppData\Local\Continuum\Anaconda2\lib\site-packages\clingkernel.py", line 24, in <module>
    from fcntl import fcntl, F_GETFL, F_SETFL
ImportError: No module named fcntl
`

**Comment by SylvainCorlay** [comment]
Windows is not really supported by cling. The windows build is merely experimental.

This should be better in the next version.
